  name: Minha Primeira linha de Montagem 

on: ^
	push: 
		branches:  [main] 

jobs:

build-e-teste: 
	runs-on: ubuntu-latest

		steps: 
			- name: 1. Pegar o chassi do carro(codigo-fonte) 
			  uses: actions/ceckout@v3 

			- name: 2. estação de build(montagem) 
			  run: echo "construido o projeto... verificando se todas as peças se encaixa!"

			- name: 3. estação de teste (controle de qualidade) 
				run: echo "rodando os testes automatizados... verificando se a porta abre e fecha!"

			



